-- MASTER REQUIREMENTS
-- CREATE USER IF NOT EXISTS 'repl'@'%' IDENTIFIED BY '1234567890';

-- GRANT REPLICATION SLAVE, REPLICATION CLIENT ON *.*
-- TO 'repl'@'%';


-- SLAVE REQUIREMENTS
CHANGE MASTER TO MASTER_HOST='master',
    MASTER_USER='repl',
    MASTER_PASSWORD='1234567890',
    MASTER_LOG_FILE='bin-logs.000003',
    MASTER_LOG_POS=154;

START SLAVE;


CREATE USER IF NOT EXISTS 'haproxy'@'%';